In [4]:
from sklearn import svm, datasets
iris = datasets.load_iris()

In [6]:
import pandas as pd
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])
df[47:52]

sepal length (cm)  sepal width (cm)  ...  petal width (cm)      flower
47                4.6               3.2  ...               0.2      setosa
48                5.3               3.7  ...               0.2      setosa
49                5.0               3.3  ...               0.2      setosa
50                7.0               3.2  ...               1.4  versicolor
51                6.4               3.2  ...               1.5  versicolor

[5 rows x 5 columns]

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3)

In [10]:
model = svm.SVC(kernel='rbf', C=30,gamma='auto')
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.9777777777777777

In [11]:
from sklearn.model_selection import cross_val_score


In [14]:
cross_val_score(svm.SVC(kernel ='linear', C=10, gamma='auto'),iris.data, iris.target, cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [15]:
cross_val_score(svm.SVC(kernel ='rbf', C=10, gamma='auto'),iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [16]:
cross_val_score(svm.SVC(kernel ='rbf', C=20, gamma='auto'),iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [19]:
import numpy as np
kernels = ['linear', 'rbf']
C = [1,10,20,]
avg_scores = {}
for k in kernels:
    for c in C:
        cv_scores = cross_val_score(svm.SVC(kernel =k, C=c, gamma='auto'),iris.data, iris.target, cv=5)
        avg_scores[k + '_' + str(c)] = np.mean(cv_scores)
avg_scores

{'linear_1': np.float64(0.9800000000000001),
 'linear_10': np.float64(0.9733333333333334),
 'linear_20': np.float64(0.9666666666666666),
 'rbf_1': np.float64(0.9800000000000001),
 'rbf_10': np.float64(0.9800000000000001),
 'rbf_20': np.float64(0.9666666666666668)}

In [20]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(svm.SVC(gamma='auto'), {'kernel':('linear', 'rbf'), 'C':[1,10,20]}, cv=5, return_train_score=False)
clf.fit(iris.data, iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00245318, 0.00133324, 0.00021839, 0.00031223, 0.00020494,
        0.00019393]),
 'std_fit_time': array([2.40491298e-03, 1.82184150e-03, 4.60679977e-05, 1.80029148e-04,
        1.73089918e-05, 5.04997341e-06]),
 'mean_score_time': array([0.00365357, 0.00020461, 0.00012922, 0.00015674, 0.00013061,
        0.00013041]),
 'std_score_time': array([4.70606411e-03, 5.38567253e-05, 1.18606953e-05, 1.93160841e-05,
        1.41600566e-05, 2.28185389e-06]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf'],
              mask=[False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}

In [21]:
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.002453      0.002405  ...        0.016330                1
1       0.001333      0.001822  ...        0.016330                1
2       0.000218      0.000046  ...        0.038873                4
3       0.000312      0.000180  ...        0.016330                1
4       0.000205      0.000017  ...        0.042164                6
5       0.000194      0.000005  ...        0.036515                5

[6 rows x 15 columns]

In [22]:
df[['param_C', 'param_kernel', 'mean_test_score']]

param_C param_kernel  mean_test_score
0        1       linear         0.980000
1        1          rbf         0.980000
2       10       linear         0.973333
3       10          rbf         0.980000
4       20       linear         0.966667
5       20          rbf         0.966667

In [23]:
dir(clf)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_refit_for_multimetric',
 '_check_scorers_accept_sample_weight',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_estimator_type',
 '_format_results',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_params_html',
 '_get_routed_params_for_fit',
 '_get_scorers',
 '_html_repr',
 '_parameter_constraints',
 '_repr_html_',
 '_repr

In [24]:
clf.best_score_

np.float64(0.9800000000000001)

In [25]:
clf.best_params_

{'C': 1, 'kernel': 'linear'}

In [27]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(svm.SVC(gamma='auto'), {'kernel':('linear', 'rbf'), 'C':[1,10,20]}, cv=5, return_train_score=False, n_iter=2)
rs.fit(iris.data, iris.target)
pd.DataFrame(rs.cv_results_)[['param_C', 'param_kernel', 'mean_test_score']]

param_C param_kernel  mean_test_score
0        1          rbf             0.98
1       10          rbf             0.98

In [29]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression


In [30]:
model_parameters = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params': {'kernel':('linear', 'rbf'), 'C':[1,10,20]}
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params': {'n_estimators':[1,5,10]}
    },
    'logistic_regression': {
        'model': LogisticRegression(solver='liblinear', multi_class='auto'),
        'params': {'C':[1,5,10]}
    }
}       

In [31]:
scores = []
for model_name, mp in model_parameters.items():
    clf =  GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(iris.data, iris.target)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })      

/Users/bhattbruh/Desktop/ml-playground/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/Users/bhattbruh/Desktop/ml-playground/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
/Users/bhattbruh/Desktop/ml-playground/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. From then on, it will always use 'multinomial'. Leave it to its default valu

In [32]:
df = pd.DataFrame(scores, columns=['model', 'best_score', 'best_params'])
df

model  best_score                   best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'linear'}
1        random_forest    0.960000           {'n_estimators': 5}
2  logistic_regression    0.966667                      {'C': 5}