In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
import numpy as np

In [2]:
iris = load_iris()


In [14]:
#LOGISTIC REGRESSION
l_scores = cross_val_score(LogisticRegression(),iris.data, iris.target)
l_scores

/Users/bhattbruh/Desktop/ml-playground/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [15]:
np.average(l_scores)

np.float64(0.9733333333333334)

In [5]:
#Decision Tree
dt_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
dt_scores

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [6]:
np.average(dt_scores)

np.float64(0.9600000000000002)

In [7]:
#Suppport Vector Machine
svm_scores = cross_val_score(SVC(), iris.data, iris.target)
svm_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [8]:
np.average(svm_scores)

np.float64(0.9666666666666666)

In [10]:
#Random Forest
rf_scores = cross_val_score(RandomForestClassifier(), iris.data, iris.target)
rf_scores


array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [11]:
np.average(rf_scores)

np.float64(0.96)

In [16]:
# Best Model is Logistic Regression with an average accuracy of 0.9733333333333334
